# site settings
title: PharmaBusters
subtitle: time to start living healthly
email: miekusn@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: Polska
phone: (+48) 600 250 638

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/NataliaPharma
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: https://www.instagram.com/pharmabusters/?hl=en
  LinkedIn: https://pl.linkedin.com/in/natalia-miekus-purwin-10915854?trk=public_profile_browsemap
  Twitter: https://twitter.com/BustersPharma
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
